pipelines:
  push-to-github:
    - step:
        name: Push to GitHub
        script:
          - git remote add github https://$GITHUB_TOKEN@github.com/chaseceeim/jscdn.git
          - git push github main
  branches:
    main:
      - step:
          name: Push to GitHub
          script:
            - git remote add github https://$GITHUB_TOKEN@github.com/chaseceeim/jscdn.git
            - git push github main
